In [17]:
def mian_value1(data,list1,row):
    n=len(data);
    yi=data[row,len(data[0])-1];
    for j in range(0,len(data[row])-1):
         yi-=list1[j]*data[row,j];
    yi=yi-list1[-1];
    return yi;

In [16]:
def step_grad(data,list1,alpha):
    slope=[0 for i in range(0,len(data[0]))];
    n=len(data);
    
    # the main value if for the yi-m1x1-m2x2------c which we need for each row 
    main_value=[0 for i in range(0,len(data))];
    for i in range(0,len(data)):
        main_value[i]=mian_value1(data,list1,i);
    
    
    # now our first work is to calculate the slope for each xi and not for c;;;;
    for i in range(0,len(slope)-1):
        temp=0;
        for j in range(0,len(main_value)):
            temp+=main_value[j]*(-1*data[j,i]);
        slope[i]=(2/n)*temp;
            
        
        
    # we  wew calculating the slope for the c here in this loop................    
    temp=0;
    for j in range(0,len(main_value)):
        temp+=main_value[j]*(-1);
    slope[-1]=(2/n)*temp;
            
   # print(slope,end="");
    
    # now we will calculate the new m for each feature........
    for i in range(0,len(list1)):
        list1[i]-=alpha*slope[i];
    return list1;
         

In [15]:
def grad(data,alpha,num_iterations):
    list1=[0 for i in range(0,len(data[0]))];
    for i in range(0,num_iterations):
        list1=step_grad(data,list1,alpha);
        #print(list1);
        #print(cost(data,list1));
    return list1;
        

In [2]:
def cost(train_data,list1):
    total_cost=0;
    for i in train_data:
        yi=0;
        for j in range(0,len(i)-1):
            yi+=list1[j]*i[j];
        yi=yi+list1[-1];
        #print(i[-1],yi);
        yi=i[-1]-yi;
        total_cost+=yi*yi;
    return total_cost/len(data);
        
    

In [30]:
def findanswer(train_data,list1):
    total_cost=0;
    for i in train_data:
        #print(len(i),len(list1));
        yi=0;
        for j in range(0,len(i)):
            yi+=list1[j]*i[j];
        yi=yi+list1[-1];
        #print(i[-1],yi);
        list1.append(yi);
    return list1;
        
    

In [35]:
import numpy as np;
from sklearn import preprocessing;
data=np.loadtxt('train1.csv',delimiter=",");
scaler=preprocessing.StandardScaler();
scaler.fit(data[0:,0:-1]);
scaler.transform(data[0:,0:-1]);
print(data);
alpha=0.1;
num_iterations=30;
list1=grad(data,alpha,num_iterations);
#print(list1);
#print(cost(data,list1));

[[   8.58   38.38 1021.03   84.37  482.26]
 [  21.79   58.2  1017.21   66.74  446.94]
 [  16.64   48.92 1011.55   78.76  452.56]
 ...
 [  29.8    69.34 1009.36   64.74  437.65]
 [  16.37   54.3  1017.94   63.63  459.97]
 [  30.11   62.04 1010.69   47.96  444.42]]


In [38]:
data=np.loadtxt('test1.csv',delimiter=",");
scaler=preprocessing.StandardScaler();
scaler.fit(data);
y_pred=findanswer(data[0:,0:-1],list1);
np.savetxt('predictions1.csv',y_pred);